shallow_clone: true

image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

for:
-
  matrix:
    only:
    - image: Visual Studio 2019
      platform: x64
  environment:
    generator: "-G\"Visual Studio 16 2019\" -A\"x64\""
-
  matrix:
    only:
    - image: Visual Studio 2019
  environment:
    generator: "-G\"Visual Studio 16 2019\""

before_build:
  - ps: |
      mkdir build
      cd build

      $cmd = "cmake .. $env:generator -DCMAKE_BUILD_TYPE=$env:CONFIGURATION $env:glmArguments"
      echo $cmd

      Invoke-Expression $cmd

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ps: |
      Get-ChildItem -recurse
      $exe = (Get-ChildItem -recurse "micro-points-viewer-demo.exe","micro-points-viewer-demo")[0].FullName
      Write-Host $exe
      & $exe

deploy: off
