shallow_clone: true

configuration:
  - Debug
  - Release

environment:
  matrix:
  - PLATFORM: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    generator: "-G\"Visual Studio 16 2019\" -A\"x64\""
  - PLATFORM: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    generator: "-G\"Visual Studio 16 2019\""
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
  - APPVEYOR_BUILD_WORKER_IMAGE: macOS

before_build:
  - ps: |
      mkdir build
      cd build

      $cmd = "cmake .. $env:generator -DCMAKE_BUILD_TYPE=$env:CONFIGURATION $env:glmArguments"
      echo $cmd

      Invoke-Expression $cmd

build_script:
  - ps: |
      $cmd = "cmake --build . -DCMAKE_BUILD_TYPE=$env:CONFIGURATION --config $env:CONFIGURATION"
      echo $cmd

      Invoke-Expression $cmd

test_script:
  - ps: |
      Get-ChildItem -recurse
      $exe = (Get-ChildItem -recurse "micro-points-viewer-demo.exe","micro-points-viewer-demo")[0].FullName
      Write-Host $exe
      & $exe

deploy: off
